name: RagBasedStockAnalyser
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - redis-py
  - openai
  - python-dotenv
  - selenium
  - beautifulsoup4
  - requests
  - pip
  - pip:
      - langchain
      - langchain-openai
      - -r requirements.txt

